### ISSUE TITLE
Create Not Working

### ISSUE THREAD

**Issue by gradyki** [gradyki/Skillz#2]
I have a 422 from my main controller on my post request.  I've tried altering the courses controller and the application controller files but I'm not sure what else to try.  I was getting an error from the authorize_request but even after I removed that to test it still wont work.  I've referenced the auth lesson, pets crud exercise and tasteville along with googling and can't find the solution.  The api post request seems to be working fine, the state variable i'm trying to create are all being captured and match the schema.

**Comment by zulays** [comment]
@gradyki please review your network tab in dev tools to see if you can read a more specific error message within the preview tab of the network
